### ISSUE TITLE
Allow map lookups, with nested keys

### ISSUE THREAD

**Issue by skx** [skx/evalfilter#159]
Given the appropriate JSON/object input it should be possible to lookup nested fields.

e.g:

         print( foo.bar.baz );

Note that I'm explicitly *not* supporting arrays, so this is invalid:

         print( foo[0].field[0].value );

**Comment by dsikes** [comment]
This seems to get the job done!! 👍  
I left my simple code bit as a comment on #162 that i used as my test.
