### ISSUE TITLE
catching an error within a script

### ISSUE THREAD

**Issue by dsikes** [skx/evalfilter#165]
So, I was using the latest version of Eval Filter and I was attempting to process some JSON data. The data should be consistent in terms of the fields that it contains, but in some cases, they are not. So, this simple script, 

```
counter = 0;
if foo.bar == true {
    counter++;
}
```
results in the following panic if foo or foo.bar is not present

```
panic: reflect: call of reflect.Value.Interface on zero Value
```

Is there a way we could support a try/catch? This would allow the system to raise an error, and then the caller can choose what to do with the error by handling it or ignoring it depending on their use case.

**Comment by skx** [comment]
Try/Catch would be a bigger change - but I can certainly make it not panic, and instead return an error.

If you could share a sample input file, then I can get started on that now.  But I can

**Comment by dsikes** [comment]
Sure, I'll email you one.

**Comment by dsikes** [comment]
So, as you'll see in the sample file I sent to you, we're actually dealing with JSON line data.
I'm wanting to run each JSON line entry through multiple scripts concurrently, to produce an aggregated view.
However, there can be some JSON events that contain some keys that others do not, and I want to ensure that the runtime doesn't exit, even if the script fails. I want the system to keep running and just log the error or allow me to handle the error in the script, if thats possible.

**Comment by skx** [comment]
>  I'm wanting to run each JSON line entry through multiple scripts concurrently, to produce an aggregated view.

I wonder if that can be the issue if you're using the same instance of the `evailfilter` object in different goroutines that's not threadsafe.

All of these should be in the same thread/goroutine:

    x := evalfilter.New( "xx" )
    err := x.Prepare()
    x.Run(obj)

State is mutated as we run - e.g. using reflection to inspect the input as/when necessary.

**Comment by dsikes** [comment]
So, I wasn't using goroutines just yet. All lines were being ran through the same evalfilter. Here is the gist of it:


```
for scanner.Scan() {
  data := strings.TrimRight(scanner.Text(), ",")
  err := json.Unmarshal([]byte(data), &event)
  if err != nil {
	  log.Fatalf(err.Error())
  }
  _, err = eval.Run(event)
  if err != nil {
	  fmt.Printf("Failed to run script: %s\n", err.Error())
	  return
  }
  fmt.Println(ret)
}
```

**Comment by skx** [comment]
I'd add a `return` in this section:

```
err := json.Unmarshal([]byte(data), &event)
  if err != nil {
	  log.Fatalf(err.Error())
  }
```

Just to make sure you're not logging a bogus JSON line, then continuing to use it.  But otherwise there's nothing wrong that I can see.
