### ISSUE TITLE
a method to serialize object.Object into a JSON compatible struct

### ISSUE THREAD

**Issue by dsikes** [skx/evalfilter#173]
With eval.Execute returning the actual object.Object, it would be very useful to have a way to convert the object.Object into a struct that can be serialized as JSON.

A simple eval script can then be used to create JSON views by plucking the data from the object, and returning a different view of the data, like in this sample script:

```
if (name == "Dan") {
  return {
    "first_name": name,
   "city": address.city,
  };
}
```

Even though my actual object contains significantly more data, in this particular case, it'd only be a JSON object that returns a first name and a city.

**Comment by skx** [comment]
I think the general case is pretty hard, because I can imagine a script which ended:

      return 3;

That's not something you can return as json unless you changed it to:

      { "return": 3}

That said I think the hash object is a good exception.  I could add a JSON interface to allow hashes, specifically, to be converted to json.  So your example would work.

(I guess similarly an array-object could be made to work, providing all the members had the same type.  So `return [3,4,5];`  or `return [ "foo", "bar", "baz"  ];`.)

Would hash-only suffice for your use-case?

**Comment by dsikes** [comment]
Yes, hash only would work. I think that is a reasonable expectation to be fair to your point as well. 
If a script returns a non hash, the caller likely wouldn't want to serialize it as JSON directly from the return of the evalfilter.

**Comment by skx** [comment]
Hrm, now I say that of course `3` is valid JSON.  As is `"Steve"`.

So I can implement for:

* Numbers.
* Strings.
* Bools.
* Hashes.
* Arrays.

That'd probably suffice for most cases.

**Comment by dsikes** [comment]
Thats true. Good point. How do you see one serializing the return object of the eval filter as JSON?

**Comment by skx** [comment]
I would probably say you'd write something like this:


     ret, err := eval.Run()
     
     helper, ok := val.(object.ToJSON)
     if !ok {
	    panic("object doesn't implement the ToJSON interface");
     }

     byte := helper.ToJSON()


At which point `byte` would contain the JSON.  (Or it could be a string.  Unsure.)

**Comment by dsikes** [comment]
That LGTM. How difficult is something like that to implement?

**Comment by skx** [comment]
I don't think it would take too long - I'd just need to define the interface and then add the `ToJSON` method to each object-type beneath `objects/`.

Handling the case of recursion / hashes will be harder than the string/bool/integers, but even so I think a couple of hours should suffice.

I'll have a stab at it tomorrow/Monday.

**Comment by dsikes** [comment]
I accidentally clicked the wrong emoji.. haha -- sounds good. Thanks for your effort.

**Comment by skx** [comment]
PR in-progress:

* Renamed the interface to `JSONAble`.
* Return value of `JSON` is `(string, error)`.
* Used/Demonstrated in `cmd/evalfilter/run_cmd.go`

TODO

* Add tests.
* Handle escaping characters.  e.g. If a string contains `"` we'd generate bogus JSON right now.

Will come back to it later in the day.

**Comment by skx** [comment]
* Test-cases added.
* Quote-handling is good, I think.

Needs more testing/experimentation, but I think it is complete now.

**Comment by dsikes** [comment]
I'll pull it in and give it a shot. Thanks for knocking it out.
