### ISSUE TITLE
syntax highlighting support with highlight.js or similar

### ISSUE THREAD

**Issue by dsikes** [skx/evalfilter#175]
How much work would it be to have syntax highlighting support using something like https://highlightjs.org/?

**Comment by skx** [comment]
It looks like highlightjs is pretty simple to support, looking over the pull-requests there to see an example of adding syntax highlighting for a new thing:

* For example https://github.com/highlightjs/highlight.js/pull/3444

You'd only need identifiers, and our keywords ("case", "default", .. "true", "while").  I guess catching strings, and numbers would be nice too.  

I could have a stab at it, though I'm not sure how likely it would be to be accepted.

**Comment by skx** [comment]
I've hacked up a quick demo, and it seems to work.  I'll past the code into this issue once I'm happier, and submit a PR to the original project.

* Clone the code.
  * `git clone git@github.com:highlightjs/highlight.js.git`
* Add my `evalfilter.js`
  *  `src/languages/evalfilter.js`
* Build the docker container to test it.
  *  `cd ~/highlight.js/ ; docker build -t highlight .`
* Launch the docker container
  * `docker run --rm -it --publish 8080:80 highlight`
* Confirm it works via the browser
  *   http://127.0.0.1:8080/tools/developer.html

**Comment by skx** [comment]
Pull-request opened, we'll see how well I did:

* https://github.com/highlightjs/highlight.js/pull/3460 

You can take the `evalfilter.js` from there.

**Comment by skx** [comment]
Turns out they're too busy to accept/maintain new languages in the highlight.js project, so I've added a snippet beneath `misc/` along with a demo.

Hope that's enough.

**Comment by dsikes** [comment]
Thanks for the quick turn around. The `misc/` example is perfect.
